spring:
  application:
    name: spring-boot-cache
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    username: postgres_user
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres_db
  flyway:
    enabled: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres_db
    user: postgres_user
    password: 123
  data:
    redis:
      host: localhost
      port: 6379
      password: 123
  cache:
    type: redis